language: ruby

sudo: false

rvm:
  - "2.2.2"

before_install:
  - gem update --system
  - gem --version
  - gem install rspec

before_script:
  - cp ./config/options.rb.sample ./config/options.rb
  - cp ./config/database.rb.sample ./config/database.rb
  - cp ./config/common.rb.sample ./config/common.rb

  - mysql -e 'create database suivi;'

script:
  - "bundle exec rake db:migrations"
  - "bundle exec rspec"
  - "bundle exec rubocop -D --format simple"

gemfile:
  - Gemfile

services:
  - mysql
  - redis-server

branches:
  only:
    - master
    - develop

notifications:
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
    on_success: change
    on_failure: change
