language: ruby
rvm:
  - 1.9.3

before_install:
  - gem update --system
  - gem --version

before_script:
  - cp ./config/options.sample ./config/options.rb
  - cp ./config/database.sample ./config/database.rb
  - cp ./config/common.rb.sample ./config/common.rb
  - cp ./config/rights_constants.sample ./config/rights_constants.rb

  - rake install
  - mysql -e 'create database suivi_test;'
  - mysql < ./db/scripts/suivi.sql
  
script: "bundle exec rake spec"

gemfile:
  - Gemfile
  
services: 
  - mysql

branches:
  only:   
    - master
    - develop

notifications:
  email:
    recepients:
      - pgl@erasme.org
