language: ruby

sudo: false

rvm:
  - "2.5.1"

before_install:
  - gem update --system
  - gem --version
  - gem install rspec

script:
  - "bundle exec rubocop -D"

gemfile:
  - gems.rb

branches:
  only:
    - develop

notifications:
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
    on_success: change
    on_failure: change
