language: ruby

sudo: false

rvm:
  - "2.2.5"

before_install:
  - gem update --system
  - gem --version
  - gem install rspec

# before_script:
#   - cp ./config/options.rb.sample ./config/options.rb
#   - cp ./config/database.rb.sample ./config/database.rb

script:
  - "bundle exec rubocop -D"
  # - mysql -e 'create database suivi;'
  # - mysql -e 'use suivi; source migrations/current_db_schema_migration.sql;'
  # - "bundle exec rake db:migrate"

gemfile:
  - gems.rb

# services:
#   - mysql

branches:
  only:
    - develop

notifications:
  slack:
    rooms:
      - erasme:IWf0zN63Kuw5HgeJVwhnhxAC#laclassebeta
    on_success: change
    on_failure: change
